[SQLDataBase]
Server = "postgres"
Database = "balance"
User = "postgres"
Password = "12345"
ApplicationName = "balance"
MaxIdleConns  = 2
MaxOpenConns = 2
ConnMaxLifetime = "5m"
Port = 5432

[ServerOpt]
ReadTimeout = "5s"
WriteTimeout = "5s"
IdleTimeout = "5s"

[Application]
Host = "localhost"
Port = 9000
